apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mabtlki1u-java-springboot
  janus-idp.io/tekton: mabtlki1u-java-springboot
  backstage.io/kubernetes-id: mabtlki1u-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mabtlki1u-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
